---
title: "Coral Data"
author: "Samantha Williams"
date: '2025-06-15'
output: html_document
---

```{r}
library(lubridate)
library(tidyverse)
library(ggplot2)
```

## 2019 Coral Data
Pre-processing and tidying:
```{r}
coral_data = read.csv("data/ClassDataset_2019_coral.csv", strip.white = T,  header = F)
head(coral_data)
coral_data=t(coral_data) # transpose the data
coral_data = coral_data[-1,] # remove row 1
colnames(coral_data) <-coral_data[1,] # assign column names
coral_data=as.data.frame(coral_data[-1:-2,-3:-4]) # remove rows and columns that won't be used
head(coral_data)

coral_data = coral_data %>%
  mutate(Site=factor(Site), # define site as a factor
         Date = dmy(paste0(Date, "-2019")), # define date as a date
         Replicate=factor(Replicate))

levels(coral_data$Site) # there are many errors in site name spelling. These must be fixed
coral_data.1 = coral_data %>%
  mutate(
    Site = fct_collapse(Site, # collapse the levels of Site 
                        "Cattle Bay" = c("Cattle Bay", "Cattle bay"),
                        "Clam Gardens" = c("Clam Gard.", "Clam Garden", "Clam Gardens"),
                        "Hazard Bay" = c("Hazard Bay", "Hazard"),
                        "Iris Point" = c("Ires Point", "Iris", "Iris Point", "Iris Pt", "Iris point"),
                        "Little Pioneer Bay South" = c("Little Pioneer Bay South", "Little Pioneer bay South", "Pioneer Bay"),
                        "Snapper Point" = c("Snapper point", "Snapper point", "Snapper Pont"),
                        "Southwest Pelorus" = c("South West Pelorus", "Southwest Pelorus vist #2", "SW Peloris", "SW Pelorus", "SW Pelorus visit #2")
    ))
levels(coral_data.1$Site) # check for duplicates

# each row is a transect. Get a count of replicate transects per site
reps.per.site.coral = coral_data.1 %>%
  group_by(Site) %>%
  summarise(nTransects = length(Site))
reps.per.site.coral

# make a figure
head(coral_data.1)

# group into benthic categories
colnames(coral_data.1)

taxa_groups <- rep(NA, ncol(coral_data.1))
taxa_groups[4:36] <- "Hard coral" # columns 4-36 are coral
taxa_groups[37:45] <- "Soft Corals"
taxa_groups[46:51] <- "Macroalgae"
taxa_groups[52:54] <- "Hard coral"
taxa_groups[55:56] <- "Soft Corals"
taxa_groups[57] <- "Hard coral"
taxa_groups[58] <- "Other" 
taxa_groups[59:61] <- "Hard coral"
taxa_groups[62:64] <- "Soft Corals"

# Name the vector with the actual column names
names(taxa_groups) <- colnames(coral_data.1)
taxon_cols <- names(taxa_groups)[!is.na(taxa_groups)]

df_long <- coral_data.1 %>%
  pivot_longer(cols = all_of(taxon_cols), names_to = "taxon", values_to = "value") %>%
  mutate(group = taxa_groups[taxon])

df_long = df_long %>%
  mutate(group=factor(group),
         value=as.numeric(value)) %>%
  group_by(Site,group,Replicate) %>%
  summarise(total = sum(value, na.rm = TRUE)) #%>%
  #pivot_wider(names_from = group, values_from = total) # run this line if you want to re-convert to wide format

# take a mean of the replicate transects
# make a function for standard error
std<- function(x) sd(x)/sqrt(length(x))

coral.mean = df_long %>%
  group_by(Site,group) %>%
  summarise(meanAbund= mean(total/10), # divide by 10 to get per m
            SE=std(total/10))
```

## Figures (2019 Coral)
```{r}
# Mean number of individuals per site
# Bar
ggplot(coral.mean, aes(x = Site, y = meanAbund, fill = group)) + 
  geom_col() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_y_continuous(expression("Mean number of individuals "*m^-2*""))

# Point range
ggplot(coral.mean, aes(x=Site,y=meanAbund, color=group)) + 
  geom_pointrange(aes(ymin=meanAbund-SE, ymax=meanAbund+SE),position=position_dodge(width=0.5)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  scale_y_continuous(expression("Mean number of individuals "*m^-2*"" * "\u00B1" * "SE"))
```

## 2025 Coral Data

```{r}
coral_2025 = read.csv("data/ClassData_CoralAbundance.csv", strip.white = T, header = T)
head(coral_2025)

# Replace column names with the first row of data
colnames(coral_2025) <- as.character(coral_2025[1, ])

# Remove that first row (since it’s now the column names)
coral_2025 <- coral_2025[-1, ]

# Reset row names
rownames(coral_2025) <- NULL

coral_2025 = coral_2025 %>%
  mutate(BuddyPair=factor(BuddyPair),
         Year=as.numeric(Year),
         Zone=factor(Zone),
         Site=factor(Site),
         Transect=factor(Transect),
         Type=factor(Type),
         Genus=factor(Genus),
         HealthStatus=factor(HealthStatus),
         Count=as.numeric(Count))

coral_2025 = coral_2025 %>%
  filter(BuddyPair != "Taylor_Gemma") # remove the mock data 

```


## 2019 and 2015 Coral Data Combined 

```{r}
# get the data in the same format and then merge
head(coral_2025)
coral_2019 <- coral_data.1 %>%
  pivot_longer(cols = all_of(taxon_cols), names_to = "taxon", values_to = "value") %>%
  mutate(group = taxa_groups[taxon])
head(coral_2019)

coral_2019 = coral_2019 %>%
  mutate(Year = as.numeric(2019),
         Transect = Replicate,
         Genus = taxon,
         HealthStatus="Healthy",
         Count = as.numeric(value),
         Type = group)

head(coral_2019)
head(coral_2025)
coral_2019_2025 = full_join(coral_2025[,-1], coral_2019)
coral_2019_2025 = coral_2019_2025[,1:8] %>%
  mutate(Site=factor(Site))
head(coral_2019_2025) # you can use this merged dataset for analysis 

coral_2019_2025 = coral_2019_2025 %>%
  mutate(Count = replace_na(Count, 0)) # remove NA values 

# rename sites to match 
coral_2019_2025 = coral_2019_2025 %>%
  mutate(Site = as.character(Site),  # convert to character for replacement
         Site = ifelse(Site == "Little Pioneer Bay North", "Pioneer", Site),
         Site = factor(Site))  # convert back to factor if needed
```

## 2019 and 2015 Coral Analysis 

Compare Total Coral Count Between 2019 and 2025 (All Sites Combined)
```{r}
coral_health_status <- coral_2019_2025 %>%
  mutate(HealthStatus = ifelse(HealthStatus == "" | is.na(HealthStatus), "Healthy", HealthStatus)) %>%
  group_by(Year, HealthStatus) %>%
  summarise(Total = sum(Count, na.rm = TRUE)) %>%
  ungroup()

ggplot(coral_health_status, aes(x = factor(Year), y = Total, fill = HealthStatus)) +
  geom_col(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Year", y = "Proportion of Coral Health Status", fill = "Health Status") +
  theme_classic() +
  theme(
    axis.title = element_text(size = 13, face = "bold"),
    axis.text = element_text(size = 11),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 11)
  )
```

```{r}
# mean coral count per transect for each year, with standard deviation and sample size as there is such a big difference in sampling effort between years.
coral_effort_adjusted <- coral_2019_2025 %>%
  group_by(Year, Transect) %>%
  summarise(Total = sum(Count, na.rm = TRUE)) %>%
  group_by(Year) %>%
  summarise(MeanCount = mean(Total), SD = sd(Total), N = n())

ggplot(coral_effort_adjusted, aes(x = factor(Year), y = MeanCount)) +
  geom_col(fill = "#69b3a2", width = 0.6) +
  geom_errorbar(aes(ymin = MeanCount - SD, ymax = MeanCount + SD), 
                width = 0.2, color = "black") +
  labs(x = "Year", y = "Mean Coral Count per Transect") +
  theme_classic() +
  theme(
    axis.title = element_text(size = 13, face = "bold"),
    axis.text = element_text(size = 11)
  )
```


## Coral Cover from PITs - 2016-2022
```{r}
# we don't have the raw data, just means of all transects per student group

coral.cover = read.csv("data/ClassDataset_2016-2022_coralcover.csv", strip.white = T, header = T)
head(coral.cover)

coral.cover = coral.cover %>%
  mutate(Year=factor(Year),
         Zone=factor(Zone),
         Site=factor(Site))

reps.per.site.cover = coral.cover %>%
  group_by(Site,Year) %>%
  summarise(nTransects = length(Site))
reps.per.site.cover

```

Plot number of transects per site 
```{r}
 
ggplot(reps.per.site.cover, aes(x=Year, y=nTransects, color=Site)) +
  geom_point() +
  geom_line( aes(group=Site)) +
  theme_classic()

reps.per.site.cover <- reps.per.site.cover %>%
  pivot_wider(
    names_from = Year,
    values_from = nTransects
  )

reps.per.site.cover
```

Merge coral cover with 2015 Data
```{r}
coral.cover.2025 = read.csv("data/ClassData_PIT.csv", strip.white = T, header = T)
head(coral.cover.2025)
# merge with long-term data

colnames(coral.cover.2025) <- as.character(coral.cover.2025[1, ])

coral.cover.2025 <- coral.cover.2025[-1, ]

rownames(coral.cover.2025) <- NULL


head(coral.cover) # long-term data
# need to calculate percent cover
# then take a mean of the three transects per buddy pair to match the format of long-term data
# note the limitations of doing such a step

# Convert necessary columns to numeric
coral.cover.2025 <- coral.cover.2025 %>%
  mutate(across(c(Acropora, Massive, OtherHard, AllAlgae, SoftCoral, Other, Total), as.numeric))

coral.cover.2025.calc = coral.cover.2025 %>%
  mutate(Acropora=Acropora/Total,
         Massive=Massive/Total,
         AllHard=OtherHard/Total, # rename the column to AllHard to match the long-term data
         AllAlgae =AllAlgae/Total,
         SoftCoral = SoftCoral/Total,
         Other=Other/Total)
head(coral.cover.2025.calc)

coral.cover.2025.summary = coral.cover.2025.calc %>%
  group_by(BuddyPair, Year, Site) %>%
  mutate(Year = factor(Year)) %>%
  summarise(across(
    c(Acropora, Massive, AllHard, SoftCoral, AllAlgae, Other), mean, .names = "{.col}"))

head(coral.cover.2025.summary)
head(coral.cover)
# formats match, now merge
coral.cover.longterm = full_join(coral.cover.2025.summary[,-1], coral.cover)
head(coral.cover.longterm) # use this for your analysis, though NOTE you will need to rename sites to match. Relevant code for re-naming sites is included in this script

```

## Coral Cover with 2015 data analysis
```{r}
coral.cover.longterm <- coral.cover.longterm %>%
  mutate(
    Site = fct_collapse(Site, # Note: can't remember if snapper is same as pioneer point
                        "Cattle Bay" = c("Cattle Bay", "Cattle bay", "Catlle Bay", "Cattle bay", "Cattle", "Cattle_Bay", "CattleMid"), 
                        "Fantome" = c("Fantom", "Fantome", "NEFantome"), 
                        "Pioneer" = c("Pioneer", "LPioneer_Bay", "Pioneer Bay", "LittlePioneerSth", "PioneerPoint", "Little Pioneer bay South", "Little Pioneer Bay South", "Little Pioneer bay South"), 
                        "NE Orpheus" = c("NE Orpheus", "NE_Orpheus", "NE ORIS", "NEOrpheus"))
  ) %>%
  filter(Site %in% c("Cattle Bay", "Fantome", "Pioneer", "NE Orpheus")) %>%
  group_by(Year, Site) %>%
  summarise(
    Acropora = mean(Acropora),
    Massive = mean(Massive),
    AllHard = mean(AllHard),
    SoftCoral = mean(SoftCoral),
    AllAlgae = mean(AllAlgae),
    Other = mean(Other),
    .groups = "drop"
  )

coral_long <- coral.cover.longterm %>%
  pivot_longer(cols = c(Acropora, Massive, AllHard, SoftCoral, AllAlgae, Other),
               names_to = "Type",
               values_to = "Percentage")


```

Plot
```{r}
# Facet by site 
# Coral Composition by Site and Year
coral_long <- coral_long %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  mutate(Year = factor(Year, levels = sort(unique(Year))))
ggplot(coral_long, aes(x = Year, y = Percentage, fill = Type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Site) +
  labs(y = "Composition Percentage") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_classic()

```

```{r}

coral_long$Year <- as.numeric(as.character(coral_long$Year))
# Substrate Type Trends by Site
ggplot(coral_long, aes(x = Year, y = Percentage, color = Type, group = Type)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  facet_wrap(~Site) +
  labs(x = "Year",
       y = "Mean Percentage Cover",
       color = "Type") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_x_continuous(breaks = unique(coral_long$Year)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

